# Loader Metadata
modLoader = "javafml"
loaderVersion = "${neoForgeVersionRange}"
license = "MIT"
issueTrackerURL = "${modIssueUrl}"

[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "${modName}"
    displayURL = "${modHomeUrl}"
    authors = "${modAuthor}"
    description = "${modDescription}"

[[mixins]]
    config = "${modId}.mixins.json"

[[mixins]]
    config = "${modId}.neoforge.mixins.json"

[[dependencies.${modId}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoForgeVersionRange}"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraftVersionRange}"
    ordering = "AFTER"
    side = "BOTH"
